export enum LibraryTab {
    Albums = 'albums',
    AlbumArtists = 'albumartists',
    Artists = 'artists',
    Authors = 'authors',
    Collections = 'collections',
    Episodes = 'episodes',
    Favorites = 'favorites',
    Genres = 'genres',
    Movies = 'movies',
    Playlists = 'playlists',
    Series = 'series',
    Songs = 'songs',
    Studios = 'studios',
    Suggestions = 'suggestions',
    Upcoming = 'upcoming',
    PhotoAlbums = 'photoalbums',
    Photos = 'photos',
    Videos = 'videos',
    Books = 'books',
    MusicVideos = 'musicvideos',
    Folders = 'folders',
    Mixed = 'mixed'
}
